bug fix

diff --git a/configs/bash_func b/configs/bash_func
--- a/configs/bash_func
+++ b/configs/bash_func
@@ -114,6 +114,7 @@ function _backup_helper
         [-h] show help info\n \
         [-e] add explanation\n \
         [-s] show logs\n \
+        [-d] delete backup files in current directory\n \
         [-c] clean the log file (${HOME}/.backup.logs)"
 }
 function _backup_remove_log
@@ -126,6 +127,35 @@ function _backup_remove_log
 function _backup_show_log
 {
     vim "${HOME}/.backup.logs"
+}
+function _backup_delete_current_dir
+{
+    file_list=()
+    count=0
+    while read line; do
+        check_result=$(echo "${line}" | grep "_[0-9]\{8\}_[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\$" | grep -i "^${cur}" | wc -l)
+        if [[ ${check_result} -eq 1 ]]; then
+            file_list=("${file_list[@]}" "${line}")
+            ((count++))
+        fi
+    done < <(ls)
+    if [[ ${count} -eq 0 ]]; then
+        echo "[FINISHED] Nothing to delete"
+    else
+        echo "${red}Deleting: ${endcolor}"
+        for item in "${file_list[@]}"; do
+           echo -e "\t${item}" 
+        done
+        read -rp "Sure to delete? (y/n): " delete_option 
+        delete_option="$(echo "${delete_option}" | tr '[:upper:]' '[:lower:]')"
+        if [[ ${delete_option} == "y" || ${delete_option} == "yes" ]]; then
+            for item in "${file_list[@]}"; do
+               rm -rf "${item}" 
+            done
+        else
+            echo "[ERROR] User quit, exiting..." 1>&2
+        fi
+    fi
 }
 function _backup_op
 {
@@ -224,20 +254,24 @@ function _backup_complete
 {
     local cur prev  
     COMP_WORDBREAKS=${COMP_WORDBREAKS//[:=]}
-    COMPREPLY=()
     prev=${COMP_WORDS[COMP_CWORD-1]}
     _get_comp_words_by_ref cur
+    COMPREPLY=()
 
     if [[ ${prev} == "-r" || ${prev} == "-rf" ]]; then
+        count=0
         while read line; do
             check_result=$(echo "${line}" | grep "_[0-9]\{8\}_[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\$" | grep -i "^${cur}" | wc -l)
             if [[ ${check_result} -eq 1 ]]; then
                 line=${line// /\\\ }
                 COMPREPLY=("${COMPREPLY[@]}" "${line}")
+                ((count++))
             fi
         done < <(ls)
+        if [[ ${count} -eq 0 ]]; then
+            COMPREPLY=("--- No Backup File ---" "")
+        fi
     fi
-    
 }
 
 function backup
@@ -254,7 +288,7 @@ function backup
     force_flag=0
     explanation=""
     unset OPTIND
-    while getopts "e:fhcrs" arg; do
+    while getopts "e:fhcrsd" arg; do
         case "${arg}" in 
             h)
                 _backup_helper
@@ -266,6 +300,10 @@ function backup
                 ;;
             s)
                 _backup_show_log 
+                ((option_count++))
+                ;;
+            d)
+                _backup_delete_current_dir
                 ((option_count++))
                 ;;
             r)
